from enum import StrEnum


class ActionState(StrEnum):
    STRONG_BUY_BIAS = "STRONG_BUY_BIAS"
    BUY_BIAS = "BUY_BIAS"
    WATCH = "WATCH"
    HOLD = "HOLD"
    REDUCE_CAUTION = "REDUCE_CAUTION"
    AVOID = "AVOID"
    SELL_BIAS = "SELL_BIAS"
    STRONG_SELL_BIAS = "STRONG_SELL_BIAS"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    EXTREME = "EXTREME"


class MarketSegment(StrEnum):
    NSE_EQUITY = "NSE_EQUITY"
    BSE_EQUITY = "BSE_EQUITY"
    INDEX = "INDEX"
    FUTURES = "FUTURES"
    OPTIONS = "OPTIONS"


class Exchange(StrEnum):
    NSE = "NSE"
    BSE = "BSE"


class InstrumentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    DELISTED = "DELISTED"
    UNKNOWN = "UNKNOWN"


class AssetClass(StrEnum):
    EQUITY = "EQUITY"
    INDEX = "INDEX"
    FUTURE = "FUTURE"
    OPTION = "OPTION"
    CURRENCY = "CURRENCY"
    COMMODITY = "COMMODITY"
    UNKNOWN = "UNKNOWN"


class Timeframe(StrEnum):
    ONE_MINUTE = "ONE_MINUTE"
    THREE_MINUTE = "THREE_MINUTE"
    FIVE_MINUTE = "FIVE_MINUTE"
    FIFTEEN_MINUTE = "FIFTEEN_MINUTE"
    THIRTY_MINUTE = "THIRTY_MINUTE"
    ONE_HOUR = "ONE_HOUR"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class DataProviderType(StrEnum):
    OFFICIAL = "OFFICIAL"
    VENDOR = "VENDOR"
    BROKER = "BROKER"
    LOCAL_SAMPLE = "LOCAL_SAMPLE"
    MANUAL = "MANUAL"
    UNKNOWN = "UNKNOWN"


class DataQualityStatus(StrEnum):
    RAW = "RAW"
    CLEANED = "CLEANED"
    NORMALIZED = "NORMALIZED"
    FEATURE_READY = "FEATURE_READY"
    BACKTEST_READY = "BACKTEST_READY"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class OptionType(StrEnum):
    CALL = "CALL"
    PUT = "PUT"


class DerivativeSide(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    UNKNOWN = "UNKNOWN"


class DecisionSource(StrEnum):
    RULE_BASED = "RULE_BASED"
    BACKTEST_DERIVED = "BACKTEST_DERIVED"
    MODEL_ASSISTED = "MODEL_ASSISTED"
    HUMAN_REVIEWED = "HUMAN_REVIEWED"
    PAPER_DERIVED = "PAPER_DERIVED"
    UNKNOWN = "UNKNOWN"


class ConfidenceMethod(StrEnum):
    RULE_SCORE = "RULE_SCORE"
    BACKTEST_SIMILARITY = "BACKTEST_SIMILARITY"
    MODEL_PROBABILITY = "MODEL_PROBABILITY"
    ENSEMBLE = "ENSEMBLE"
    HUMAN_OVERRIDE = "HUMAN_OVERRIDE"
    UNKNOWN = "UNKNOWN"


class RegimeLabel(StrEnum):
    TREND_EXPANSION = "TREND_EXPANSION"
    PULLBACK_RECOVERY = "PULLBACK_RECOVERY"
    RANGE_COMPRESSION = "RANGE_COMPRESSION"
    BREAKDOWN = "BREAKDOWN"
    REVERSAL_ATTEMPT = "REVERSAL_ATTEMPT"
    HIGH_VOLATILITY_CAUTION = "HIGH_VOLATILITY_CAUTION"
    LOW_VOLATILITY_DRIFT = "LOW_VOLATILITY_DRIFT"
    CHOP = "CHOP"
    UNKNOWN = "UNKNOWN"


class MarketDataKind(StrEnum):
    OHLCV_BAR = "OHLCV_BAR"
    OPTIONS_CHAIN_SNAPSHOT = "OPTIONS_CHAIN_SNAPSHOT"
    FUTURES_BASIS_SNAPSHOT = "FUTURES_BASIS_SNAPSHOT"
    MARKET_STATE_SNAPSHOT = "MARKET_STATE_SNAPSHOT"
    REGIME_SNAPSHOT = "REGIME_SNAPSHOT"
    UNKNOWN = "UNKNOWN"


class SnapshotQuality(StrEnum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class DataLakeZone(StrEnum):
    RAW = "RAW"
    CLEANED = "CLEANED"
    NORMALIZED = "NORMALIZED"
    FEATURE_READY = "FEATURE_READY"
    BACKTEST_READY = "BACKTEST_READY"
    RESEARCH_ARTIFACTS = "RESEARCH_ARTIFACTS"


class DatasetFormat(StrEnum):
    PARQUET = "PARQUET"
    CSV = "CSV"
    JSONL = "JSONL"
    DUCKDB = "DUCKDB"
    UNKNOWN = "UNKNOWN"


class DatasetKind(StrEnum):
    OHLCV = "OHLCV"
    OPTIONS_CHAIN = "OPTIONS_CHAIN"
    FUTURES_BASIS = "FUTURES_BASIS"
    MARKET_STATE = "MARKET_STATE"
    REGIME = "REGIME"
    FEATURE_SET = "FEATURE_SET"
    BACKTEST_RESULT = "BACKTEST_RESULT"
    RESEARCH_ARTIFACT = "RESEARCH_ARTIFACT"
    UNKNOWN = "UNKNOWN"


class CacheNamespace(StrEnum):
    HEALTH = "HEALTH"
    CONFIG = "CONFIG"
    MARKET_STATE = "MARKET_STATE"
    DECISION_OBJECT = "DECISION_OBJECT"
    RESEARCH_LAKE = "RESEARCH_LAKE"
    TIMESERIES = "TIMESERIES"
    DATABASE = "DATABASE"
    TEMPORARY = "TEMPORARY"


class CacheValueKind(StrEnum):
    JSON = "JSON"
    TEXT = "TEXT"
    BYTES = "BYTES"
    UNKNOWN = "UNKNOWN"


class EventType(StrEnum):
    INGESTION_REQUESTED = "INGESTION_REQUESTED"
    INGESTION_COMPLETED = "INGESTION_COMPLETED"
    NORMALIZATION_REQUESTED = "NORMALIZATION_REQUESTED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    FEATURE_COMPUTATION_REQUESTED = "FEATURE_COMPUTATION_REQUESTED"
    FEATURE_COMPUTATION_COMPLETED = "FEATURE_COMPUTATION_COMPLETED"
    REGIME_UPDATE_REQUESTED = "REGIME_UPDATE_REQUESTED"
    REGIME_UPDATE_COMPLETED = "REGIME_UPDATE_COMPLETED"
    OPTIONS_UPDATE_REQUESTED = "OPTIONS_UPDATE_REQUESTED"
    OPTIONS_UPDATE_COMPLETED = "OPTIONS_UPDATE_COMPLETED"
    RISK_UPDATE_REQUESTED = "RISK_UPDATE_REQUESTED"
    RISK_UPDATE_COMPLETED = "RISK_UPDATE_COMPLETED"
    DECISION_GENERATION_REQUESTED = "DECISION_GENERATION_REQUESTED"
    DECISION_GENERATION_COMPLETED = "DECISION_GENERATION_COMPLETED"
    BACKTEST_REQUESTED = "BACKTEST_REQUESTED"
    BACKTEST_COMPLETED = "BACKTEST_COMPLETED"
    PAPER_LAB_REQUESTED = "PAPER_LAB_REQUESTED"
    PAPER_LAB_COMPLETED = "PAPER_LAB_COMPLETED"
    AUDIT_RECORDED = "AUDIT_RECORDED"
    SYSTEM_HEALTH_RECORDED = "SYSTEM_HEALTH_RECORDED"
    UNKNOWN = "UNKNOWN"


class EventSource(StrEnum):
    API = "API"
    WORKER = "WORKER"
    SCHEDULER = "SCHEDULER"
    SYSTEM = "SYSTEM"
    TEST = "TEST"
    UNKNOWN = "UNKNOWN"


class EventPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class StreamNamespace(StrEnum):
    INGESTION = "INGESTION"
    NORMALIZATION = "NORMALIZATION"
    FEATURES = "FEATURES"
    REGIME = "REGIME"
    OPTIONS = "OPTIONS"
    RISK = "RISK"
    DECISIONS = "DECISIONS"
    BACKTESTS = "BACKTESTS"
    PAPER_LAB = "PAPER_LAB"
    AUDIT = "AUDIT"
    SYSTEM = "SYSTEM"


class EventBackboneMode(StrEnum):
    MEMORY = "MEMORY"
    KAFKA = "KAFKA"
    REDPANDA = "REDPANDA"
    DISABLED = "DISABLED"


class TopicNamespace(StrEnum):
    INGESTION = "INGESTION"
    NORMALIZATION = "NORMALIZATION"
    FEATURES = "FEATURES"
    REGIME = "REGIME"
    OPTIONS = "OPTIONS"
    RISK = "RISK"
    DECISIONS = "DECISIONS"
    BACKTESTS = "BACKTESTS"
    PAPER_LAB = "PAPER_LAB"
    AUDIT = "AUDIT"
    SYSTEM = "SYSTEM"
    WAREHOUSE = "WAREHOUSE"
    RESEARCH_LAKE = "RESEARCH_LAKE"
    UNKNOWN = "UNKNOWN"


class EventBackboneStatus(StrEnum):
    DISABLED = "DISABLED"
    MEMORY_FALLBACK = "MEMORY_FALLBACK"
    CONFIGURED = "CONFIGURED"
    REACHABLE = "REACHABLE"
    UNREACHABLE = "UNREACHABLE"
    UNKNOWN = "UNKNOWN"


class WorkerRole(StrEnum):
    INGESTION_WORKER = "INGESTION_WORKER"
    NORMALIZATION_WORKER = "NORMALIZATION_WORKER"
    FEATURE_WORKER = "FEATURE_WORKER"
    REGIME_WORKER = "REGIME_WORKER"
    OPTIONS_WORKER = "OPTIONS_WORKER"
    RISK_WORKER = "RISK_WORKER"
    DECISION_WORKER = "DECISION_WORKER"
    BACKTEST_WORKER = "BACKTEST_WORKER"
    PAPER_LAB_WORKER = "PAPER_LAB_WORKER"
    AUDIT_WORKER = "AUDIT_WORKER"
    SYSTEM_HEALTH_WORKER = "SYSTEM_HEALTH_WORKER"
    TEST_WORKER = "TEST_WORKER"
    UNKNOWN = "UNKNOWN"


class JobPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class WorkerStatus(StrEnum):
    DISABLED = "DISABLED"
    IDLE = "IDLE"
    BUSY = "BUSY"
    HEALTHY = "HEALTHY"
    UNHEALTHY = "UNHEALTHY"
    UNKNOWN = "UNKNOWN"


class MarketDataRequestKind(StrEnum):
    HISTORICAL_BARS = "HISTORICAL_BARS"
    LATEST_BAR = "LATEST_BAR"
    INSTRUMENT_MASTER = "INSTRUMENT_MASTER"
    OPTIONS_CHAIN = "OPTIONS_CHAIN"
    FUTURES_CHAIN = "FUTURES_CHAIN"
    HEALTH_CHECK = "HEALTH_CHECK"
    UNKNOWN = "UNKNOWN"


class AdjustmentMode(StrEnum):
    RAW = "RAW"
    SPLIT_ADJUSTED = "SPLIT_ADJUSTED"
    DIVIDEND_ADJUSTED = "DIVIDEND_ADJUSTED"
    TOTAL_RETURN_ADJUSTED = "TOTAL_RETURN_ADJUSTED"
    UNKNOWN = "UNKNOWN"


class ProviderCapability(StrEnum):
    INSTRUMENT_MASTER = "INSTRUMENT_MASTER"
    HISTORICAL_BARS = "HISTORICAL_BARS"
    LATEST_BAR = "LATEST_BAR"
    OPTIONS_CHAIN = "OPTIONS_CHAIN"
    FUTURES_CHAIN = "FUTURES_CHAIN"
    CORPORATE_ACTIONS = "CORPORATE_ACTIONS"
    HEALTH_CHECK = "HEALTH_CHECK"


class ProviderStatus(StrEnum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    PLANNED = "PLANNED"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class WarehouseTableKind(StrEnum):
    OHLCV_ANALYTICAL = "OHLCV_ANALYTICAL"
    OPTIONS_CHAIN_ANALYTICAL = "OPTIONS_CHAIN_ANALYTICAL"
    FUTURES_BASIS_ANALYTICAL = "FUTURES_BASIS_ANALYTICAL"
    MARKET_STATE_ANALYTICAL = "MARKET_STATE_ANALYTICAL"
    REGIME_ANALYTICAL = "REGIME_ANALYTICAL"
    DECISION_OBJECT_ANALYTICAL = "DECISION_OBJECT_ANALYTICAL"
    BACKTEST_RESULT_ANALYTICAL = "BACKTEST_RESULT_ANALYTICAL"
    FEATURE_ANALYTICAL = "FEATURE_ANALYTICAL"
    UNKNOWN = "UNKNOWN"


class WarehouseEngine(StrEnum):
    MERGE_TREE = "MERGE_TREE"
    REPLACING_MERGE_TREE = "REPLACING_MERGE_TREE"
    SUMMING_MERGE_TREE = "SUMMING_MERGE_TREE"
    AGGREGATING_MERGE_TREE = "AGGREGATING_MERGE_TREE"
    UNKNOWN = "UNKNOWN"


class WarehouseStatus(StrEnum):
    DISABLED = "DISABLED"
    MEMORY_FALLBACK = "MEMORY_FALLBACK"
    CONFIGURED = "CONFIGURED"
    REACHABLE = "REACHABLE"
    UNREACHABLE = "UNREACHABLE"
    UNKNOWN = "UNKNOWN"


class FeatureValueType(StrEnum):
    FLOAT = "FLOAT"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    STRING = "STRING"
    TIMESTAMP = "TIMESTAMP"
    CATEGORY = "CATEGORY"
    JSON = "JSON"
    UNKNOWN = "UNKNOWN"


class FeatureEntityType(StrEnum):
    INSTRUMENT = "INSTRUMENT"
    INSTRUMENT_TIMEFRAME = "INSTRUMENT_TIMEFRAME"
    MARKET = "MARKET"
    SECTOR = "SECTOR"
    PORTFOLIO = "PORTFOLIO"
    STRATEGY = "STRATEGY"
    UNKNOWN = "UNKNOWN"


class FeatureFrequency(StrEnum):
    REALTIME = "REALTIME"
    INTRADAY = "INTRADAY"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    EVENT_DRIVEN = "EVENT_DRIVEN"
    STATIC = "STATIC"
    UNKNOWN = "UNKNOWN"


class FeatureStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    DISABLED = "DISABLED"
    UNKNOWN = "UNKNOWN"


class FeatureComputationMode(StrEnum):
    RULE_BASED = "RULE_BASED"
    BATCH = "BATCH"
    STREAMING = "STREAMING"
    MODEL_DERIVED = "MODEL_DERIVED"
    MANUAL = "MANUAL"
    UNKNOWN = "UNKNOWN"


class FeatureQualityStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"


class FixtureKind(StrEnum):
    SYNTHETIC_OHLCV = "SYNTHETIC_OHLCV"
    SYNTHETIC_INSTRUMENT_MASTER = "SYNTHETIC_INSTRUMENT_MASTER"
    SYNTHETIC_MARKET_DATA_BATCH = "SYNTHETIC_MARKET_DATA_BATCH"
    UNKNOWN = "UNKNOWN"


class FixtureStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DISABLED = "DISABLED"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"
