from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum


class ResearchArtifactRegistryStage(StrEnum):
    PLANNING = "planning"
    AUDIT_ONLY = "audit_only"
    BLOCKED = "blocked"
    UNKNOWN = "unknown"


class ResearchArtifactKind(StrEnum):
    PAPER_REFERENCE = "PAPER_REFERENCE"
    DATASET_REFERENCE = "DATASET_REFERENCE"
    HYPOTHESIS_REFERENCE = "HYPOTHESIS_REFERENCE"
    EXPERIMENT_REFERENCE = "EXPERIMENT_REFERENCE"
    NOTEBOOK_REFERENCE = "NOTEBOOK_REFERENCE"
    CODE_REFERENCE = "CODE_REFERENCE"
    REPORT_REFERENCE = "REPORT_REFERENCE"
    BACKTEST_REFERENCE_PLACEHOLDER = "BACKTEST_REFERENCE_PLACEHOLDER"
    STRATEGY_REFERENCE_PLACEHOLDER = "STRATEGY_REFERENCE_PLACEHOLDER"
    UNKNOWN = "UNKNOWN"


class ResearchArtifactReferenceKind(StrEnum):
    PAPER_REFERENCE_PLACEHOLDER = "PAPER_REFERENCE_PLACEHOLDER"
    DATASET_REFERENCE_PLACEHOLDER = "DATASET_REFERENCE_PLACEHOLDER"
    HYPOTHESIS_REFERENCE_PLACEHOLDER = "HYPOTHESIS_REFERENCE_PLACEHOLDER"
    EXPERIMENT_REFERENCE_PLACEHOLDER = "EXPERIMENT_REFERENCE_PLACEHOLDER"
    NOTEBOOK_REFERENCE_PLACEHOLDER = "NOTEBOOK_REFERENCE_PLACEHOLDER"
    CODE_REFERENCE_PLACEHOLDER = "CODE_REFERENCE_PLACEHOLDER"
    REPORT_REFERENCE_PLACEHOLDER = "REPORT_REFERENCE_PLACEHOLDER"
    PROVENANCE_REFERENCE_PLACEHOLDER = "PROVENANCE_REFERENCE_PLACEHOLDER"
    UNKNOWN = "UNKNOWN"


class ResearchArtifactProvenanceSourceType(StrEnum):
    PAPER_REFERENCE = "PAPER_REFERENCE"
    DATASET_REFERENCE = "DATASET_REFERENCE"
    LOCAL_REFERENCE_PLACEHOLDER = "LOCAL_REFERENCE_PLACEHOLDER"
    NOTEBOOK_REFERENCE = "NOTEBOOK_REFERENCE"
    CODE_REFERENCE = "CODE_REFERENCE"
    REPORT_REFERENCE = "REPORT_REFERENCE"
    SYNTHETIC_CONTEXT = "SYNTHETIC_CONTEXT"
    UNKNOWN = "UNKNOWN"


class ResearchArtifactLifecycleStatus(StrEnum):
    PLACEHOLDER = "PLACEHOLDER"
    REFERENCED = "REFERENCED"
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    DEFERRED = "DEFERRED"
    UNKNOWN = "UNKNOWN"


class ResearchArtifactForbiddenInteractionKind(StrEnum):
    ACTIVE_INGESTION = "ACTIVE_INGESTION"
    PERSISTENT_STORAGE = "PERSISTENT_STORAGE"
    FILE_UPLOAD = "FILE_UPLOAD"
    FILE_DOWNLOAD = "FILE_DOWNLOAD"
    PAPER_INGESTION = "PAPER_INGESTION"
    PAPER_PARSING = "PAPER_PARSING"
    PDF_PARSING = "PDF_PARSING"
    ARXIV_INGESTION = "ARXIV_INGESTION"
    LLM_ANALYSIS = "LLM_ANALYSIS"
    METHOD_EXTRACTION = "METHOD_EXTRACTION"
    STRATEGY_EXTRACTION = "STRATEGY_EXTRACTION"
    STRATEGY_GENERATION = "STRATEGY_GENERATION"
    STRATEGY_CODE_GENERATION = "STRATEGY_CODE_GENERATION"
    SIGNAL_GENERATION = "SIGNAL_GENERATION"
    FACTOR_GENERATION = "FACTOR_GENERATION"
    ALPHA_GENERATION = "ALPHA_GENERATION"
    BACKTESTING = "BACKTESTING"
    OPTIMIZATION = "OPTIMIZATION"
    RECOMMENDATION_GENERATION = "RECOMMENDATION_GENERATION"
    ACTION_GENERATION = "ACTION_GENERATION"
    CONFIDENCE_SCORING = "CONFIDENCE_SCORING"
    DECISION_OBJECT_GENERATION = "DECISION_OBJECT_GENERATION"
    READINESS_TO_TRADE = "READINESS_TO_TRADE"
    BROKER_CONTROL = "BROKER_CONTROL"
    APPROVAL_CONTROL = "APPROVAL_CONTROL"
    OVERRIDE_CONTROL = "OVERRIDE_CONTROL"
    EXECUTION = "EXECUTION"
    EXTERNAL_CALL = "EXTERNAL_CALL"
    DATABASE_WRITE = "DATABASE_WRITE"
    OBJECT_STORAGE_WRITE = "OBJECT_STORAGE_WRITE"
    UNKNOWN = "UNKNOWN"


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def normalize_datetime(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def non_empty_text(value: str, field_name: str) -> str:
    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field_name} cannot be empty")
    return normalized


def sanitize_text_list(values: list[str]) -> list[str]:
    sanitized: list[str] = []
    for value in values:
        normalized = value.strip()
        if normalized:
            sanitized.append(normalized)
    return sanitized


SAFE_LIFECYCLE_STATUSES = {
    ResearchArtifactLifecycleStatus.PLACEHOLDER,
    ResearchArtifactLifecycleStatus.REFERENCED,
    ResearchArtifactLifecycleStatus.DRAFT,
    ResearchArtifactLifecycleStatus.REVIEW_REQUIRED,
    ResearchArtifactLifecycleStatus.BLOCKED,
    ResearchArtifactLifecycleStatus.DEFERRED,
}

