from enum import StrEnum


class ValidationSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class ValidationStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"


class ValidationScope(StrEnum):
    INSTRUMENT = "INSTRUMENT"
    INSTRUMENT_UNIVERSE = "INSTRUMENT_UNIVERSE"
    MARKET_DATA_BAR = "MARKET_DATA_BAR"
    MARKET_DATA_REQUEST = "MARKET_DATA_REQUEST"
    MARKET_DATA_RESPONSE = "MARKET_DATA_RESPONSE"
    OPTIONS_CHAIN_SNAPSHOT = "OPTIONS_CHAIN_SNAPSHOT"
    DATASET_MANIFEST = "DATASET_MANIFEST"
    FEATURE_SNAPSHOT = "FEATURE_SNAPSHOT"
    FEATURE_QUALITY_REPORT = "FEATURE_QUALITY_REPORT"
    WAREHOUSE_TABLE_CONTRACT = "WAREHOUSE_TABLE_CONTRACT"
    PROVIDER_RESPONSE = "PROVIDER_RESPONSE"
    UNKNOWN = "UNKNOWN"


class QualityGateDecision(StrEnum):
    ALLOW = "ALLOW"
    WARN = "WARN"
    BLOCK = "BLOCK"
    UNKNOWN = "UNKNOWN"


class ValidationRuleType(StrEnum):
    REQUIRED_FIELD = "REQUIRED_FIELD"
    RANGE_CHECK = "RANGE_CHECK"
    CONSISTENCY_CHECK = "CONSISTENCY_CHECK"
    UNIQUENESS_CHECK = "UNIQUENESS_CHECK"
    TIMESTAMP_CHECK = "TIMESTAMP_CHECK"
    SOURCE_REFERENCE_CHECK = "SOURCE_REFERENCE_CHECK"
    SCHEMA_CHECK = "SCHEMA_CHECK"
    CONTRACT_CHECK = "CONTRACT_CHECK"
    SECURITY_CHECK = "SECURITY_CHECK"
    CUSTOM = "CUSTOM"
