from fastapi import FastAPI

from stark_terminal_api.routes.analytics_foundation import router as analytics_foundation_router
from stark_terminal_api.routes.cache import router as cache_router
from stark_terminal_api.routes.config import router as config_router
from stark_terminal_api.routes.data_quality import router as data_quality_router
from stark_terminal_api.routes.database import router as database_router
from stark_terminal_api.routes.decision_boundary import router as decision_boundary_router
from stark_terminal_api.routes.decision_desk import router as decision_desk_router
from stark_terminal_api.routes.decision_desk_api import router as decision_desk_api_router
from stark_terminal_api.routes.decision_display import router as decision_display_router
from stark_terminal_api.routes.decision_evidence import router as decision_evidence_router
from stark_terminal_api.routes.decision_evidence_validation import (
    router as decision_evidence_validation_router,
)
from stark_terminal_api.routes.decision_human_review import router as decision_human_review_router
from stark_terminal_api.routes.decision_readiness_api import router as decision_readiness_api_router
from stark_terminal_api.routes.decision_safety import router as decision_safety_router
from stark_terminal_api.routes.event_backbone import router as event_backbone_router
from stark_terminal_api.routes.features import router as features_router
from stark_terminal_api.routes.fixtures import router as fixtures_router
from stark_terminal_api.routes.health import router as health_router
from stark_terminal_api.routes.instrument_metadata import router as instrument_metadata_router
from stark_terminal_api.routes.instruments import router as instruments_router
from stark_terminal_api.routes.local_file_provider import router as local_file_provider_router
from stark_terminal_api.routes.local_sample_provider import router as local_sample_provider_router
from stark_terminal_api.routes.market_data_batches import router as market_data_batches_router
from stark_terminal_api.routes.numerical_analytics import router as numerical_analytics_router
from stark_terminal_api.routes.provider_guardrails import router as provider_guardrails_router
from stark_terminal_api.routes.provider_readiness import router as provider_readiness_router
from stark_terminal_api.routes.regime_analytics import router as regime_analytics_router
from stark_terminal_api.routes.regime_features import router as regime_features_router
from stark_terminal_api.routes.relationship_analytics import router as relationship_analytics_router
from stark_terminal_api.routes.retail_dashboard import router as retail_dashboard_router
from stark_terminal_api.routes.retail_dashboard_api import router as retail_dashboard_api_router
from stark_terminal_api.routes.retail_dashboard_boundary import router as retail_dashboard_boundary_router
from stark_terminal_api.routes.retail_dashboard_display import router as retail_dashboard_display_router
from stark_terminal_api.routes.retail_decision_console import router as retail_decision_console_router
from stark_terminal_api.routes.retail_trader_experience import router as retail_trader_experience_router
from stark_terminal_api.routes.retail_trader_experience_api import router as retail_trader_experience_api_router
from stark_terminal_api.routes.retail_trader_experience_boundary import (
    router as retail_trader_experience_boundary_router,
)
from stark_terminal_api.routes.retail_trader_experience_display import (
    router as retail_trader_experience_display_router,
)
from stark_terminal_api.routes.research_artifact_registry import router as research_artifact_registry_router
from stark_terminal_api.routes.research_artifact_registry_api import (
    router as research_artifact_registry_api_router,
)
from stark_terminal_api.routes.research_artifact_registry_boundary import (
    router as research_artifact_registry_boundary_router,
)
from stark_terminal_api.routes.research_artifact_registry_display import (
    router as research_artifact_registry_display_router,
)
from stark_terminal_api.routes.research_artifact_index import router as research_artifact_index_router
from stark_terminal_api.routes.research_artifact_index_api import router as research_artifact_index_api_router
from stark_terminal_api.routes.research_artifact_index_boundary import (
    router as research_artifact_index_boundary_router,
)
from stark_terminal_api.routes.research_artifact_index_display import (
    router as research_artifact_index_display_router,
)
from stark_terminal_api.routes.research_metadata_graph import router as research_metadata_graph_router
from stark_terminal_api.routes.research_metadata_graph_api import router as research_metadata_graph_api_router
from stark_terminal_api.routes.research_metadata_graph_display import (
    router as research_metadata_graph_display_router,
)
from stark_terminal_api.routes.research_knowledge_map import router as research_knowledge_map_router
from stark_terminal_api.routes.research_knowledge_map_api import router as research_knowledge_map_api_router
from stark_terminal_api.routes.research_knowledge_map_display import (
    router as research_knowledge_map_display_router,
)
from stark_terminal_api.routes.research_lake import router as research_lake_router
from stark_terminal_api.routes.returns_analytics import router as returns_analytics_router
from stark_terminal_api.routes.risk_analytics import router as risk_analytics_router
from stark_terminal_api.routes.strategy_research_workspace import router as strategy_research_workspace_router
from stark_terminal_api.routes.strategy_research_workspace_api import (
    router as strategy_research_workspace_api_router,
)
from stark_terminal_api.routes.strategy_research_workspace_boundary import (
    router as strategy_research_workspace_boundary_router,
)
from stark_terminal_api.routes.strategy_research_workspace_display import (
    router as strategy_research_workspace_display_router,
)
from stark_terminal_api.routes.streams import router as streams_router
from stark_terminal_api.routes.synthetic_ohlcv_storage import router as synthetic_ohlcv_storage_router
from stark_terminal_api.routes.synthetic_ohlcv_exports import router as synthetic_ohlcv_exports_router
from stark_terminal_api.routes.time_series_diagnostics import router as time_series_diagnostics_router
from stark_terminal_api.routes.timeseries import router as timeseries_router
from stark_terminal_api.routes.warehouse import router as warehouse_router
from stark_terminal_api.routes.workers import router as workers_router

app = FastAPI(
    title="Stark Terminal API",
    version="0.1.0",
    description="Prompt 107 institutional-grade foundation API shell.",
)

app.include_router(health_router)
app.include_router(analytics_foundation_router)
app.include_router(numerical_analytics_router)
app.include_router(returns_analytics_router)
app.include_router(risk_analytics_router)
app.include_router(relationship_analytics_router)
app.include_router(time_series_diagnostics_router)
app.include_router(regime_analytics_router)
app.include_router(regime_features_router)
app.include_router(decision_desk_router)
app.include_router(decision_evidence_router)
app.include_router(decision_safety_router)
app.include_router(decision_desk_api_router)
app.include_router(decision_readiness_api_router)
app.include_router(decision_display_router)
app.include_router(decision_evidence_validation_router)
app.include_router(decision_human_review_router)
app.include_router(decision_boundary_router)
app.include_router(retail_dashboard_router)
app.include_router(retail_dashboard_api_router)
app.include_router(retail_dashboard_display_router)
app.include_router(retail_dashboard_boundary_router)
app.include_router(retail_decision_console_router)
app.include_router(retail_trader_experience_router)
app.include_router(retail_trader_experience_api_router)
app.include_router(retail_trader_experience_display_router)
app.include_router(retail_trader_experience_boundary_router)
app.include_router(strategy_research_workspace_router)
app.include_router(strategy_research_workspace_api_router)
app.include_router(strategy_research_workspace_display_router)
app.include_router(strategy_research_workspace_boundary_router)
app.include_router(research_artifact_registry_router)
app.include_router(research_artifact_registry_api_router)
app.include_router(research_artifact_registry_display_router)
app.include_router(research_artifact_registry_boundary_router)
app.include_router(research_artifact_index_router)
app.include_router(research_artifact_index_api_router)
app.include_router(research_artifact_index_display_router)
app.include_router(research_artifact_index_boundary_router)
app.include_router(research_metadata_graph_router)
app.include_router(research_metadata_graph_api_router)
app.include_router(research_metadata_graph_display_router)
app.include_router(research_knowledge_map_router)
app.include_router(research_knowledge_map_api_router)
app.include_router(research_knowledge_map_display_router)
app.include_router(config_router)
app.include_router(database_router)
app.include_router(timeseries_router)
app.include_router(research_lake_router)
app.include_router(cache_router)
app.include_router(streams_router)
app.include_router(event_backbone_router)
app.include_router(data_quality_router)
app.include_router(instrument_metadata_router)
app.include_router(market_data_batches_router)
app.include_router(synthetic_ohlcv_storage_router)
app.include_router(synthetic_ohlcv_exports_router)
app.include_router(provider_guardrails_router)
app.include_router(provider_readiness_router)
app.include_router(local_sample_provider_router)
app.include_router(local_file_provider_router)
app.include_router(workers_router)
app.include_router(instruments_router)
app.include_router(warehouse_router)
app.include_router(features_router)
app.include_router(fixtures_router)
