from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from audit_foundation import run_audit


ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = [
    "README.md",
    "AGENTS.md",
    "PROJECT_MAP.md",
    "pyproject.toml",
    ".gitignore",
    ".env.example",
    "docs/NORTH_STAR.md",
    "docs/ARCHITECTURE.md",
    "docs/TECH_STACK.md",
    "docs/INFRASTRUCTURE_STACK.md",
    "docs/ANALYTICS_STACK.md",
    "docs/SAFETY_RULES.md",
    "docs/DATA_POLICY.md",
    "docs/DOMAIN_MODEL.md",
    "docs/CONFIGURATION.md",
    "docs/DATABASE_FOUNDATION.md",
    "docs/TIMESCALEDB_FOUNDATION.md",
    "docs/TIMESERIES_SCHEMA.md",
    "docs/RESEARCH_LAKE_FOUNDATION.md",
    "docs/PARQUET_DATA_ZONES.md",
    "docs/DUCKDB_FOUNDATION.md",
    "docs/REDIS_CACHE_FOUNDATION.md",
    "docs/CACHE_KEY_POLICY.md",
    "docs/REDIS_STREAMS_FOUNDATION.md",
    "docs/EVENT_PIPELINE_POLICY.md",
    "docs/EVENT_ENVELOPE_SPEC.md",
    "docs/WORKER_SYSTEM_FOUNDATION.md",
    "docs/WORKER_ROLE_POLICY.md",
    "docs/JOB_ENVELOPE_SPEC.md",
    "docs/INSTRUMENT_MASTER_FOUNDATION.md",
    "docs/MARKET_DATA_PROVIDER_CONTRACTS.md",
    "docs/SYMBOL_NORMALIZATION_POLICY.md",
    "docs/CLICKHOUSE_WAREHOUSE_FOUNDATION.md",
    "docs/ANALYTICAL_TABLE_CONTRACTS.md",
    "docs/WAREHOUSE_QUERY_POLICY.md",
    "docs/FEATURE_REGISTRY_FOUNDATION.md",
    "docs/FEATURE_DEFINITION_SPEC.md",
    "docs/FEATURE_QUALITY_POLICY.md",
    "docs/TRAINING_SERVING_CONSISTENCY_POLICY.md",
    "docs/KAFKA_REDPANDA_FOUNDATION.md",
    "docs/EVENT_BACKBONE_TOPIC_POLICY.md",
    "docs/DURABLE_EVENT_ENVELOPE_SPEC.md",
    "docs/DATA_QUALITY_FRAMEWORK.md",
    "docs/VALIDATION_RULE_SPEC.md",
    "docs/QUALITY_GATE_POLICY.md",
    "docs/DATA_QUALITY_REPORT_SPEC.md",
    "docs/SYNTHETIC_MARKET_DATA_FIXTURES.md",
    "docs/OHLCV_FIXTURE_CONTRACTS.md",
    "docs/SAMPLE_DATA_POLICY.md",
    "docs/INSTRUMENT_PERSISTENCE_FOUNDATION.md",
    "docs/INSTRUMENT_REPOSITORY_POLICY.md",
    "docs/MARKET_DATA_BATCH_PERSISTENCE.md",
    "docs/BATCH_METADATA_POLICY.md",
    "docs/DATA_FOUNDATION_AUDIT.md",
    "docs/DATA_PERSISTENCE_BOUNDARY.md",
    "docs/SYNTHETIC_DATA_SAFETY_AUDIT.md",
    "docs/DATA_FOUNDATION_NEXT_PHASE.md",
    "docs/SYNTHETIC_OHLCV_STORAGE_FOUNDATION.md",
    "docs/TIMESCALE_SYNTHETIC_STORAGE_POLICY.md",
    "docs/SYNTHETIC_OHLCV_RESEARCH_LAKE_EXPORT.md",
    "docs/OHLCV_EXPORT_MANIFEST_POLICY.md",
    "docs/PROVIDER_ADAPTER_IMPLEMENTATION_PLAN.md",
    "docs/PROVIDER_GUARDRAIL_POLICY.md",
    "docs/PROVIDER_APPROVAL_WORKFLOW.md",
    "docs/PROVIDER_COMPLIANCE_CHECKLIST.md",
    "docs/LOCAL_SAMPLE_PROVIDER_ADAPTER.md",
    "docs/LOCAL_SAMPLE_PROVIDER_POLICY.md",
    "docs/DATA_FOUNDATION_MILESTONE_AUDIT.md",
    "docs/SYNTHETIC_STORAGE_EXPORT_AUDIT.md",
    "docs/PROVIDER_GUARDRAIL_AUDIT.md",
    "docs/LOCAL_SAMPLE_PROVIDER_AUDIT.md",
    "docs/DATA_FOUNDATION_MILESTONE_NEXT_PHASE.md",
    "docs/REAL_PROVIDER_READINESS_CHECKLIST.md",
    "docs/PROVIDER_CANDIDATE_SELECTION_POLICY.md",
    "docs/PROVIDER_RISK_SCORING_POLICY.md",
    "docs/PROVIDER_CAPABILITY_GAP_ANALYSIS.md",
    "docs/LOCAL_FILE_PROVIDER_ADAPTER.md",
    "docs/LOCAL_FILE_PROVIDER_POLICY.md",
    "docs/LOCAL_FILE_PATH_SAFETY.md",
    "docs/PROVIDER_ADAPTER_MILESTONE_AUDIT.md",
    "docs/PROVIDER_BOUNDARY_AUDIT.md",
    "docs/PROVIDER_NO_EXTERNAL_CALLS_AUDIT.md",
    "docs/PROVIDER_NEXT_PHASE_PLAN.md",
    "docs/MILESTONE_A_B_AUDIT.md",
    "docs/REPO_INVENTORY.md",
    "docs/API_SURFACE_INVENTORY.md",
    "docs/SAFETY_AUDIT.md",
    "docs/NEXT_PHASE_PLAN.md",
    "docs/DECISION_OBJECT_SPEC.md",
    "docs/ROADMAP.md",
    "docs/PROMPT_LOG.md",
    "apps/api/stark_terminal_api/__init__.py",
    "apps/api/stark_terminal_api/main.py",
    "apps/api/stark_terminal_api/routes/__init__.py",
    "apps/api/stark_terminal_api/routes/cache.py",
    "apps/api/stark_terminal_api/routes/config.py",
    "apps/api/stark_terminal_api/routes/data_quality.py",
    "apps/api/stark_terminal_api/routes/database.py",
    "apps/api/stark_terminal_api/routes/event_backbone.py",
    "apps/api/stark_terminal_api/routes/features.py",
    "apps/api/stark_terminal_api/routes/fixtures.py",
    "apps/api/stark_terminal_api/routes/health.py",
    "apps/api/stark_terminal_api/routes/instrument_metadata.py",
    "apps/api/stark_terminal_api/routes/instruments.py",
    "apps/api/stark_terminal_api/routes/market_data_batches.py",
    "apps/api/stark_terminal_api/routes/synthetic_ohlcv_storage.py",
    "apps/api/stark_terminal_api/routes/synthetic_ohlcv_exports.py",
    "apps/api/stark_terminal_api/routes/provider_guardrails.py",
    "apps/api/stark_terminal_api/routes/provider_readiness.py",
    "apps/api/stark_terminal_api/routes/local_sample_provider.py",
    "apps/api/stark_terminal_api/routes/local_file_provider.py",
    "apps/api/stark_terminal_api/routes/research_lake.py",
    "apps/api/stark_terminal_api/routes/streams.py",
    "apps/api/stark_terminal_api/routes/timeseries.py",
    "apps/api/stark_terminal_api/routes/warehouse.py",
    "apps/api/stark_terminal_api/routes/workers.py",
    "apps/desktop/stark_terminal_desktop/__init__.py",
    "apps/desktop/stark_terminal_desktop/main.py",
    "packages/core/stark_terminal_core/__init__.py",
    "packages/core/stark_terminal_core/config/__init__.py",
    "packages/core/stark_terminal_core/config/settings.py",
    "packages/core/stark_terminal_core/domain/__init__.py",
    "packages/core/stark_terminal_core/domain/audit.py",
    "packages/core/stark_terminal_core/domain/enums.py",
    "packages/core/stark_terminal_core/domain/identifiers.py",
    "packages/core/stark_terminal_core/domain/instrument.py",
    "packages/core/stark_terminal_core/domain/market_data.py",
    "packages/core/stark_terminal_core/domain/market_data_batch.py",
    "packages/core/stark_terminal_core/domain/market_data_contracts.py",
    "packages/core/stark_terminal_core/domain/derivatives.py",
    "packages/core/stark_terminal_core/domain/options.py",
    "packages/core/stark_terminal_core/domain/decision_object.py",
    "packages/core/stark_terminal_core/serialization/__init__.py",
    "packages/core/stark_terminal_core/serialization/json.py",
    "packages/data_platform/stark_terminal_data_platform/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/README.md",
    "packages/data_platform/stark_terminal_data_platform/db/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/db/base.py",
    "packages/data_platform/stark_terminal_data_platform/db/engine.py",
    "packages/data_platform/stark_terminal_data_platform/db/session.py",
    "packages/data_platform/stark_terminal_data_platform/db/health.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/instrument.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/data_provider.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/audit.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/decision.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/timeseries.py",
    "packages/data_platform/stark_terminal_data_platform/db/models/market_data_batch.py",
    "packages/data_platform/stark_terminal_data_platform/timeseries/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/timeseries/health.py",
    "packages/data_platform/stark_terminal_data_platform/timeseries/hypertables.py",
    "packages/data_platform/stark_terminal_data_platform/timeseries/README.md",
    "packages/data_platform/stark_terminal_data_platform/lake/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/lake/paths.py",
    "packages/data_platform/stark_terminal_data_platform/lake/zones.py",
    "packages/data_platform/stark_terminal_data_platform/lake/manifest.py",
    "packages/data_platform/stark_terminal_data_platform/lake/duckdb_client.py",
    "packages/data_platform/stark_terminal_data_platform/lake/parquet_io.py",
    "packages/data_platform/stark_terminal_data_platform/lake/registry.py",
    "packages/data_platform/stark_terminal_data_platform/lake/health.py",
    "packages/data_platform/stark_terminal_data_platform/lake/README.md",
    "packages/data_platform/stark_terminal_data_platform/cache/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/cache/keys.py",
    "packages/data_platform/stark_terminal_data_platform/cache/serialization.py",
    "packages/data_platform/stark_terminal_data_platform/cache/client.py",
    "packages/data_platform/stark_terminal_data_platform/cache/memory.py",
    "packages/data_platform/stark_terminal_data_platform/cache/health.py",
    "packages/data_platform/stark_terminal_data_platform/cache/README.md",
    "packages/data_platform/stark_terminal_data_platform/streams/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/streams/names.py",
    "packages/data_platform/stark_terminal_data_platform/streams/events.py",
    "packages/data_platform/stark_terminal_data_platform/streams/serialization.py",
    "packages/data_platform/stark_terminal_data_platform/streams/memory.py",
    "packages/data_platform/stark_terminal_data_platform/streams/producer.py",
    "packages/data_platform/stark_terminal_data_platform/streams/consumer.py",
    "packages/data_platform/stark_terminal_data_platform/streams/health.py",
    "packages/data_platform/stark_terminal_data_platform/streams/README.md",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/topics.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/envelopes.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/serialization.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/memory.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/producer.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/consumer.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/health.py",
    "packages/data_platform/stark_terminal_data_platform/event_backbone/README.md",
    "packages/data_platform/stark_terminal_data_platform/quality/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/quality/enums.py",
    "packages/data_platform/stark_terminal_data_platform/quality/issues.py",
    "packages/data_platform/stark_terminal_data_platform/quality/rules.py",
    "packages/data_platform/stark_terminal_data_platform/quality/results.py",
    "packages/data_platform/stark_terminal_data_platform/quality/reports.py",
    "packages/data_platform/stark_terminal_data_platform/quality/gates.py",
    "packages/data_platform/stark_terminal_data_platform/quality/validators.py",
    "packages/data_platform/stark_terminal_data_platform/quality/builtins.py",
    "packages/data_platform/stark_terminal_data_platform/quality/registry.py",
    "packages/data_platform/stark_terminal_data_platform/quality/health.py",
    "packages/data_platform/stark_terminal_data_platform/quality/README.md",
    "packages/data_platform/stark_terminal_data_platform/fixtures/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/manifests.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/synthetic_ohlcv.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/catalog.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/validation.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/parquet.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/health.py",
    "packages/data_platform/stark_terminal_data_platform/fixtures/README.md",
    "packages/data_platform/stark_terminal_data_platform/repositories/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/repositories/instruments.py",
    "packages/data_platform/stark_terminal_data_platform/repositories/market_data_batches.py",
    "packages/data_platform/stark_terminal_data_platform/repositories/ohlcv_bars.py",
    "packages/data_platform/stark_terminal_data_platform/repositories/README.md",
    "packages/data_platform/stark_terminal_data_platform/services/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/services/instruments.py",
    "packages/data_platform/stark_terminal_data_platform/services/market_data_batches.py",
    "packages/data_platform/stark_terminal_data_platform/services/synthetic_ohlcv_storage.py",
    "packages/data_platform/stark_terminal_data_platform/services/README.md",
    "packages/data_platform/stark_terminal_data_platform/exports/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/exports/synthetic_ohlcv.py",
    "packages/data_platform/stark_terminal_data_platform/exports/README.md",
    "packages/data_platform/stark_terminal_data_platform/workers/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/workers/roles.py",
    "packages/data_platform/stark_terminal_data_platform/workers/jobs.py",
    "packages/data_platform/stark_terminal_data_platform/workers/results.py",
    "packages/data_platform/stark_terminal_data_platform/workers/base.py",
    "packages/data_platform/stark_terminal_data_platform/workers/registry.py",
    "packages/data_platform/stark_terminal_data_platform/workers/harness.py",
    "packages/data_platform/stark_terminal_data_platform/workers/health.py",
    "packages/data_platform/stark_terminal_data_platform/workers/README.md",
    "packages/data_platform/stark_terminal_data_platform/instruments/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/normalization.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/universe.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/master.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/fixtures.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/health.py",
    "packages/data_platform/stark_terminal_data_platform/instruments/README.md",
    "packages/data_platform/stark_terminal_data_platform/providers/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/providers/base.py",
    "packages/data_platform/stark_terminal_data_platform/providers/contracts.py",
    "packages/data_platform/stark_terminal_data_platform/providers/guardrails.py",
    "packages/data_platform/stark_terminal_data_platform/providers/approval.py",
    "packages/data_platform/stark_terminal_data_platform/providers/readiness.py",
    "packages/data_platform/stark_terminal_data_platform/providers/candidates.py",
    "packages/data_platform/stark_terminal_data_platform/providers/selection.py",
    "packages/data_platform/stark_terminal_data_platform/providers/local_sample.py",
    "packages/data_platform/stark_terminal_data_platform/providers/local_file.py",
    "packages/data_platform/stark_terminal_data_platform/providers/registry.py",
    "packages/data_platform/stark_terminal_data_platform/providers/health.py",
    "packages/data_platform/stark_terminal_data_platform/providers/README.md",
    "packages/data_platform/stark_terminal_data_platform/warehouse/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/tables.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/ddl.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/client.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/memory.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/health.py",
    "packages/data_platform/stark_terminal_data_platform/warehouse/README.md",
    "packages/data_platform/stark_terminal_data_platform/features/__init__.py",
    "packages/data_platform/stark_terminal_data_platform/features/definitions.py",
    "packages/data_platform/stark_terminal_data_platform/features/feature_sets.py",
    "packages/data_platform/stark_terminal_data_platform/features/values.py",
    "packages/data_platform/stark_terminal_data_platform/features/quality.py",
    "packages/data_platform/stark_terminal_data_platform/features/lineage.py",
    "packages/data_platform/stark_terminal_data_platform/features/registry.py",
    "packages/data_platform/stark_terminal_data_platform/features/health.py",
    "packages/data_platform/stark_terminal_data_platform/features/README.md",
    "packages/analytics/stark_terminal_analytics/__init__.py",
    "packages/analytics/stark_terminal_analytics/README.md",
    "packages/research/stark_terminal_research/__init__.py",
    "packages/research/stark_terminal_research/README.md",
    "tests/test_api_health.py",
    "tests/test_api_config.py",
    "tests/test_api_database_health.py",
    "tests/test_api_timeseries_health.py",
    "tests/test_api_research_lake_health.py",
    "tests/test_api_cache_health.py",
    "tests/test_api_streams_health.py",
    "tests/test_api_instruments_health.py",
    "tests/test_api_warehouse_health.py",
    "tests/test_api_features_health.py",
    "tests/test_settings.py",
    "tests/test_database_settings.py",
    "tests/test_database_models.py",
    "tests/test_database_health.py",
    "tests/test_alembic_foundation.py",
    "tests/test_timescale_settings.py",
    "tests/test_timeseries_models.py",
    "tests/test_timeseries_health.py",
    "tests/test_timeseries_alembic_foundation.py",
    "tests/test_timeseries_docs_status.py",
    "tests/test_lake_settings.py",
    "tests/test_lake_paths_zones.py",
    "tests/test_dataset_manifest.py",
    "tests/test_parquet_io.py",
    "tests/test_duckdb_client.py",
    "tests/test_lake_health.py",
    "tests/test_research_lake_docs_status.py",
    "tests/test_cache_settings.py",
    "tests/test_cache_keys.py",
    "tests/test_cache_serialization.py",
    "tests/test_cache_memory.py",
    "tests/test_cache_client.py",
    "tests/test_cache_health.py",
    "tests/test_cache_docs_status.py",
    "tests/test_stream_settings.py",
    "tests/test_stream_names.py",
    "tests/test_stream_event_envelope.py",
    "tests/test_stream_serialization.py",
    "tests/test_stream_memory.py",
    "tests/test_stream_producer_consumer.py",
    "tests/test_stream_health.py",
    "tests/test_stream_docs_status.py",
    "tests/test_event_backbone_settings.py",
    "tests/test_event_backbone_topics.py",
    "tests/test_event_backbone_envelopes.py",
    "tests/test_event_backbone_serialization.py",
    "tests/test_event_backbone_memory.py",
    "tests/test_event_backbone_producer_consumer.py",
    "tests/test_event_backbone_health.py",
    "tests/test_api_event_backbone_health.py",
    "tests/test_event_backbone_docs_status.py",
    "tests/test_quality_settings.py",
    "tests/test_quality_issues_rules.py",
    "tests/test_quality_results_reports.py",
    "tests/test_quality_gates.py",
    "tests/test_quality_validators_base.py",
    "tests/test_quality_builtin_validators.py",
    "tests/test_quality_registry.py",
    "tests/test_quality_health.py",
    "tests/test_api_data_quality.py",
    "tests/test_quality_docs_status.py",
    "tests/test_fixture_settings.py",
    "tests/test_fixture_manifests.py",
    "tests/test_synthetic_ohlcv_generation.py",
    "tests/test_fixture_catalog.py",
    "tests/test_fixture_validation.py",
    "tests/test_fixture_parquet.py",
    "tests/test_fixture_health.py",
    "tests/test_api_fixtures.py",
    "tests/test_fixture_docs_status.py",
    "tests/test_instrument_repository.py",
    "tests/test_instrument_service.py",
    "tests/test_instrument_persistence_validation.py",
    "tests/test_api_instrument_metadata.py",
    "tests/test_instrument_persistence_docs_status.py",
    "tests/test_market_data_batch_domain.py",
    "tests/test_market_data_batch_orm.py",
    "tests/test_market_data_batch_repository.py",
    "tests/test_market_data_batch_service.py",
    "tests/test_market_data_batch_validation.py",
    "tests/test_api_market_data_batches.py",
    "tests/test_market_data_batch_docs_status.py",
    "tests/test_ohlcv_bar_repository.py",
    "tests/test_synthetic_ohlcv_storage_service.py",
    "tests/test_synthetic_ohlcv_storage_validation.py",
    "tests/test_api_synthetic_ohlcv_storage.py",
    "tests/test_synthetic_ohlcv_storage_docs_status.py",
    "tests/test_synthetic_ohlcv_export_contracts.py",
    "tests/test_synthetic_ohlcv_export_service.py",
    "tests/test_synthetic_ohlcv_export_validation.py",
    "tests/test_synthetic_ohlcv_export_parquet.py",
    "tests/test_api_synthetic_ohlcv_exports.py",
    "tests/test_synthetic_ohlcv_export_docs_status.py",
    "tests/test_provider_guardrail_contracts.py",
    "tests/test_provider_approval_workflow.py",
    "tests/test_provider_readiness.py",
    "tests/test_api_provider_guardrails.py",
    "tests/test_provider_guardrail_docs_status.py",
    "tests/test_provider_no_external_calls_guardrail.py",
    "tests/test_local_sample_provider_adapter.py",
    "tests/test_local_sample_provider_guardrails.py",
    "tests/test_local_sample_provider_validation.py",
    "tests/test_api_local_sample_provider.py",
    "tests/test_local_sample_provider_docs_status.py",
    "tests/test_local_sample_provider_no_external_calls.py",
    "tests/test_provider_candidate_profiles.py",
    "tests/test_provider_selection_criteria.py",
    "tests/test_provider_risk_scoring.py",
    "tests/test_provider_capability_gap_analysis.py",
    "tests/test_provider_candidate_registry.py",
    "tests/test_api_provider_readiness.py",
    "tests/test_provider_readiness_docs_status.py",
    "tests/test_provider_readiness_no_external_calls.py",
    "tests/test_local_file_provider_contracts.py",
    "tests/test_local_file_provider_path_safety.py",
    "tests/test_local_file_provider_adapter.py",
    "tests/test_local_file_provider_validation.py",
    "tests/test_api_local_file_provider.py",
    "tests/test_local_file_provider_docs_status.py",
    "tests/test_local_file_provider_no_external_calls.py",
    "tests/test_provider_adapter_milestone_audit_docs.py",
    "tests/test_provider_no_external_calls_milestone.py",
    "tests/test_provider_no_sdk_or_scraping_dependencies.py",
    "tests/test_provider_api_milestone_safety.py",
    "tests/test_provider_boundary_readiness.py",
    "tests/test_provider_adapter_milestone_readiness.py",
    "tests/test_data_foundation_milestone_audit_docs.py",
    "tests/test_synthetic_storage_export_boundaries.py",
    "tests/test_provider_guardrail_milestone_safety.py",
    "tests/test_local_sample_provider_milestone_safety.py",
    "tests/test_data_foundation_milestone_api_safety.py",
    "tests/test_data_foundation_milestone_readiness.py",
    "tests/test_data_foundation_audit_docs.py",
    "tests/test_data_foundation_no_real_ingestion.py",
    "tests/test_data_foundation_persistence_boundaries.py",
    "tests/test_data_foundation_api_safety.py",
    "tests/test_data_foundation_readiness.py",
    "tests/test_worker_settings.py",
    "tests/test_worker_roles.py",
    "tests/test_job_envelope.py",
    "tests/test_worker_results.py",
    "tests/test_worker_base.py",
    "tests/test_worker_registry.py",
    "tests/test_worker_harness.py",
    "tests/test_worker_health.py",
    "tests/test_api_workers_health.py",
    "tests/test_worker_docs_status.py",
    "tests/test_instrument_settings.py",
    "tests/test_symbol_normalization.py",
    "tests/test_instrument_universe.py",
    "tests/test_instrument_master.py",
    "tests/test_market_data_contracts.py",
    "tests/test_provider_contracts.py",
    "tests/test_provider_registry.py",
    "tests/test_instrument_provider_health.py",
    "tests/test_instrument_docs_status.py",
    "tests/test_warehouse_settings.py",
    "tests/test_warehouse_tables.py",
    "tests/test_warehouse_ddl.py",
    "tests/test_warehouse_memory.py",
    "tests/test_warehouse_client.py",
    "tests/test_warehouse_health.py",
    "tests/test_warehouse_docs_status.py",
    "tests/test_feature_settings.py",
    "tests/test_feature_definitions.py",
    "tests/test_feature_sets.py",
    "tests/test_feature_values.py",
    "tests/test_feature_quality.py",
    "tests/test_feature_lineage.py",
    "tests/test_feature_registry.py",
    "tests/test_feature_health.py",
    "tests/test_feature_docs_status.py",
    "tests/test_milestone_a_b_audit_docs.py",
    "tests/test_api_surface_inventory.py",
    "tests/test_safety_no_execution.py",
    "tests/test_safe_settings_snapshot_audit.py",
    "tests/test_repo_inventory_consistency.py",
    "tests/test_foundation_health_surface.py",
    "tests/test_domain_identifiers.py",
    "tests/test_instrument_schema.py",
    "tests/test_market_data_schema.py",
    "tests/test_derivatives_options_schema.py",
    "tests/test_decision_object_schema.py",
    "tests/test_project_foundation.py",
    "tests/test_docs_stack_lock.py",
    "alembic.ini",
    "alembic/env.py",
    "alembic/script.py.mako",
    "alembic/versions/.gitkeep",
    "alembic/versions/0001_initial_metadata_tables.py",
    "alembic/versions/0002_operational_timeseries_tables.py",
    "alembic/versions/0003_market_data_batch_metadata.py",
    "migrations/README.md",
    "scripts/audit_foundation.py",
]

STACK_KEYWORDS = [
    "PostgreSQL",
    "TimescaleDB",
    "DuckDB",
    "Parquet",
    "Redis",
    "Redis Streams",
    "Kafka",
    "Redpanda",
    "ClickHouse",
    "Feast",
    "NumPy",
    "SciPy",
    "Polars",
    "Numba",
    "JAX",
    "CuPy",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "QuantLib",
    "CVXPY",
    "VaR",
    "Expected Shortfall",
    "Transformers",
    "Sentence Transformers",
    "SQLAlchemy",
    "Alembic",
    "system of record",
    "no execution APIs",
    "operational time-series",
    "hypertable",
    "OHLCV",
    "no market data ingestion",
    "research lake",
    "data zones",
    "cache",
    "memory fallback",
    "TTL",
    "event pipeline",
    "event envelope",
    "durable event backbone",
    "topic policy",
    "DurableEventEnvelope",
    "Data Quality",
    "validation framework",
    "validation rule",
    "quality gate",
    "validation report",
    "no analytics signals",
    "local-only",
    "test/dev only",
    "no real market data",
    "Instrument Metadata Persistence",
    "InstrumentRepository",
    "InstrumentMetadataService",
    "Market Data Batch Persistence",
    "Data Foundation Audit",
    "Data Persistence Boundary",
    "Synthetic Data Safety Audit",
    "TimescaleDB Synthetic OHLCV Storage Foundation",
    "Synthetic OHLCV Storage",
    "validation-before-storage",
    "Synthetic OHLCV Research Lake Export",
    "DatasetManifest",
    "validation-before-export",
    "no production research lake writes by default",
    "Provider Adapter",
    "Provider Adapter Guardrails",
    "Local Sample Provider",
    "Data Foundation Milestone Audit",
    "Synthetic Storage Export Audit",
    "Provider Guardrail Audit",
    "Local Sample Provider Audit",
    "Data Foundation Milestone Next Phase",
    "no analytics/signals/decisions",
    "Guardrail",
    "approval workflow",
    "compliance checklist",
    "no credentials",
    "no provider SDKs",
    "LOCAL_SAMPLE",
    "local-only",
    "no trading signals",
    "Real Provider Readiness",
    "Prompt 23",
    "Prompt 24",
    "Prompt 25",
    "Candidate Selection",
    "risk scoring",
    "capability gap",
    "no SDKs",
    "no production approval",
    "Local File Provider",
    "local-file-only",
    "path safety",
    "no arbitrary file read API",
    "Provider Adapter Milestone Audit",
    "Provider Boundary Audit",
    "Provider No External Calls Audit",
    "Provider Next Phase Plan",
    "batch metadata",
    "MarketDataBatchMetadata",
    "MarketDataBatchRepository",
    "MarketDataBatchMetadataService",
    "validation-before-persistence",
    "no full OHLCV bars",
    "no full OHLCV production persistence",
    "producer",
    "consumer",
    "Kafka/Redpanda Event Backbone",
    "Worker System",
    "job envelope",
    "worker role",
    "in-process harness",
    "Redis Streams future wiring",
    "Instrument Master",
    "Market Data Provider",
    "symbol normalization",
    "synthetic",
    "no external calls",
    "no scraping",
    "analytical warehouse",
    "table contracts",
    "DDL helpers",
    "memory query recorder",
    "no automatic table creation",
    "Feature Registry",
    "feature definition",
    "feature quality",
    "lineage",
    "training/serving consistency",
    "Feast planned",
    "no feature computation",
    "Milestone A/B",
    "audit",
    "API surface",
    "safety audit",
    "repo inventory",
    "Mac mini M2",
    "Windows-native",
]


def collect_docs_text() -> str:
    return "\n".join(path.read_text(encoding="utf-8") for path in (ROOT / "docs").glob("*.md"))


def run_pytest() -> int:
    result = subprocess.run(
        [sys.executable, "-m", "pytest"],
        cwd=ROOT,
        check=False,
        text=True,
    )
    return result.returncode


def main() -> int:
    print("Stark Terminal foundation verification")

    missing_files = [path for path in REQUIRED_FILES if not (ROOT / path).exists()]
    if missing_files:
        print("Missing required files:")
        for path in missing_files:
            print(f"  - {path}")
        return 1

    docs_text = collect_docs_text()
    missing_keywords = [keyword for keyword in STACK_KEYWORDS if keyword not in docs_text]
    if missing_keywords:
        print("Missing institutional stack keywords:")
        for keyword in missing_keywords:
            print(f"  - {keyword}")
        return 1

    print(f"Required files: {len(REQUIRED_FILES)} present")
    print(f"Institutional stack keywords: {len(STACK_KEYWORDS)} present")
    audit_results = run_audit()
    audit_failures = [result for result in audit_results if not result.passed]
    if audit_failures:
        print("Audit checks failed:")
        for result in audit_failures:
            print(f"  - {result.name}: {result.detail}")
        return 1
    print(f"Audit checks: {len(audit_results)} passed")
    print("Running pytest...")

    pytest_exit = run_pytest()
    if pytest_exit != 0:
        print("Pytest failed.")
        return pytest_exit

    print("Foundation verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
